### ISSUE TITLE
Broken Tabs

### ISSUE THREAD

**Issue by tomjn** [youknowriad/blockbook#11] opened 2020-07-23 18:30 UTC
Most tabs are broken, reporting `SyntaxError: nothing to repeat` in the dev console. This is happening currently on the demonstration site at https://youknowriad.github.io/blockbook/

**Comment by youknowriad** [comment] 2020-07-23 19:06
@tomjn Hi There! I'm having trouble reproducing that? Any more details? Could it be one of your browser extensions?

**Comment by tomjn** [comment] 2020-07-23 19:08
So I can't reproduce this in chrome, but it's reproducible in Firefox:

```
SyntaxError: nothing to repeat
    isAllowed https://youknowriad.github.io/blockbook/:1
    K https://youknowriad.github.io/blockbook/:1
    O https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:21
    g https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:21
    l https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:21
    ee https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:21
    registerStore https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:21
    b https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:21
    Pu https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:9
    oc https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:338
    hl https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:338
    unstable_runWithPriority https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:346
    Wo https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:338
    ml https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:338
    fl https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:338
    B https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:346
    onmessage https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:346
main.1e0cd035664cb736a8a2.js:338:82385
    ec https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:338
    callback https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:338
    pa https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:338
    ac https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:338
    bl https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:338
    unstable_runWithPriority https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:346
    Wo https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:338
    pl https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:338
    Zc https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:338
    Xo https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:338
    unstable_runWithPriority https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:346
    Wo https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:338
    Xo https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:338
    Uo https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:338
    hl https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:338
    unstable_runWithPriority https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:346
    Wo https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:338
    ml https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:338
    fl https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:338
    B https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:346
    onmessage https://youknowriad.github.io/blockbook/main.1e0cd035664cb736a8a2.js:346
```

**Comment by youknowriad** [comment] 2020-07-23 19:13
Interesting, I still don't see it on Firefox 77. I'm updating to see whether It's just on the new version.

**Comment by youknowriad** [comment] 2020-07-23 19:14
Same, nothing so far for me 🤔

**Comment by senadir** [comment] 2020-07-26 13:13
I tested Firefox 78 on macOS Catalina and I can't reproduce.

**Comment by tomjn** [comment] 2020-07-26 15:40
I believe the problem may be the react dev tools add on

**Comment by youknowriad** [comment] 2020-07-30 12:15
Going to close this for now as I'm having trouble reproducing it.

**Closed by youknowriad** 2020-07-30 12:15 UTC
Labels: needs more info
